#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  curl --disable --silent --show-error --location --max-time 30 "https://raw.githubusercontent.com/kaamelott-gifboard/kaamelott-gifboard/main/gifs.json" | jq '[ .[] | {id: .slug, value: .quote, character: (.characters_speaking|join(", ")), url: ("https://kaamelott-gifboard.fr/gifs/" + .filename) } ]' >"kaamelott_gif.json"

  INDEXER_INPUT="kaamelott_gif.json" make run-indexer
  rm "kaamelott_gif.json"
}

main "${@}"
