apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kaamebott
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.75"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kaamebott
    image:
      name: vibioh/kaamebott
      tag: "202109010725" # {"$imagepolicy": "default:flux-kaamebott-api:tag"}
    config:
      KAAMEBOTT_LOGGER_JSON: "true"
      KAAMEBOTT_DB_HOST: kaamebott-db
      KAAMEBOTT_DB_PORT: "80"
      KAAMEBOTT_DB_NAME: kaamebott
      KAAMEBOTT_DISCORD_APPLICATION_ID: "882376778943971349"
      KAAMEBOTT_DISCORD_PUBLIC_KEY: d3acdcf3d7dc08c1d32714b3a51b0db4e40041059e075b274d94326011c20a31
    secrets:
      KAAMEBOTT_DISCORD_CLIENT_ID: AgCs/Rzu/fdNIfH3qtZrKBPJuTzNXUnugHaVFrzr5nlPzqNXIMyYzgt41EmFegPNPJ2GNMYNVZ7Sx/3sFECCRIb4Jh57SZewJ7hlZ4cwEAh3FeI3fIeW+EWKQMHoqVaPFJynr6KWFg05St7A6SVDK12lDNavnWKUqpu+/tP4W+pEM3I2nAj9ol22CMtgKuv4FrPeY8I5N0aXjaIDUROtVhmbxg1eNMBSu8J58DgfguCbfxjGcd/9CYRtProNiktx5UGf4wXg8G0kQMAs054MwU6PQ6JZTcQTN9j+1ejHmfcr3R5dR6rLmdO2oEnh2QoNLNP3ve0+zDrLnvLwAbu+EZ0BfiHFMS8FMLWVBHQtLmYSbUmRcBlXEQFlBUFMs38I3kU8LliLOuL/ky7RXVl7k0VrMHCfgFbb7+OG6DpRdUqOfoP/JzCR6T2mAneFiHY3xPb6UEq9zFfxZdnc3fa9zGRisAQ47rHhTZtlF6eWBYZWFdlj5kD7RqUL44unvZIYMBjz87gb15BhJG/eyMGaKf8IU6sIC2hsGPUDtpPNh7akb/i7gu/VpXfozSRbNPaSiJ/0mBqnzEdkEYh8m6pYzUHE1NBUX8nTZrjU+zNm+0AlzBepifG8mU0DF60y7wk+a7d6bBYZgsOoLxINiba9SqlNM9aOEaNNue3HeIfsrqSGkLF4A5eYHsBmoQG89iFJ6IJQAZ/SxUlpcHrUYdx0MlILVLY=
      KAAMEBOTT_DISCORD_CLIENT_SECRET: AgDkeiCpc+cMf8yiS0iTM7fgLoo4GFpR+Mk1j967i0/DfVWkiK3cYfS+iHaysd3Qk3lDFwWq7JtdmYcFIdYQrQYWUv3tN4jVRQotsfWooTfDOjs/jT3xFjbYSB/2leUfWDpKZO3hBZYyWKyHeuUE6lZaWJMqScax4R5gpDaG0bLB2Zjx25LJ//NlA4uWfKmTEV7br9I0aT1f0XHcmD03MthBzjDKNNLh3OUCPgHHZGA9p0Lu0noGWRVKpJp1bwTWYuTzP1fxHh3z/d6TUmRbTXmh3BHvb/yA8X+c3xK8rWPpvChZ6GnZHZseANZWoa6TuFdm2v9STq+klUTL5252+DovDBYEmYJRHhR7K0Mw3Da1ep8Zz5fCllgnIgyV9dFRK/3y9aoEkUEHjt2xHhI0Grn7K083elmyhDq+XptyjIozPW1Jqf9OPx6fWEC/nmjuzo86H3KeVAEBACLlA3oeCZ4asAbYAP2g0jRI+yj31zDupIN+SkZe1WrBJW+wxn/xGkG6WHX3ZyHMmOmwJ6BV1P+OGTw/ISEOAB8l9WT0y8zc3U4FWgz3HTgi8KdeH5xe9w5cE0jnXYkJjVx1U/agX4L2S59ecxH1W9gYklKGj76klIm34juynSdtkhFMDzyH3r31qFSyHjpuzeEd9jXN1upeQbDhcgitjQsbkTBN4GtORAVsOBleB6beFcM43oyftdM2yeB0Nd4KRVvN6w++gZhINfAdTOedvzoJ7BvZJKbPjA==
      KAAMEBOTT_DB_USER: AgAawfgv9QL+8y+4YGszWVklKgfxTvtHhnpL4Kcbat3QqUZqaLhaLexAZhiBLRpsLSbLPMrm6LvvKp8Vk5ZcOR338llY7rLogrOqipDJgh+G5G14VHfaXsTrapWDtG3q4CmDXkpdvokl+Blx7re9QdznuDLfX1ULjg/49rurFcR0RagSfQnAqnOK7VSFjRK2kffpCkrRtRRX8nBcncjoQK8sXZKPAD/hwmse6iRSi8NiLqaZ/2qM2RLdv08t6OfwZrOS7MeL2TlLZ8k/rPaAPS99JEb2py1j7fzawbKicO0hZJ8tnEZiTk8R81nmrhNxfNdjH0jv381wgcojo0VFVZ8nf6PTPFhW2Ue7DEwwNgoyJ6mTe9766C0KI67/QgCo1VrWFBqjxuoC0YSE/YMr69vqYIzfQd5rUdmrSjUMUCDdNkidrR/GOes77JKBQWtGm9+8dQlb9AJOUmQZnLx9fYmnXMSAGRjzI71lO8mrUBYWN/xyfQlYXW4uN5znlVOsiHFYfxITMTF7tJ+bBeuhOO+awJ6oeOrQXWd5IwpJZrKxtA4F889ZsFNr/EpycpZ3SuwUBaD/2rKAaL6X9CaeXdgxvoRq+UdOvwaA6BpL9oL46PhxjxMwxyS85hVmKVAeKreVKbCL1eu7aeBVGLCgVLMzVy4/iDgROSX6L/WoVixqPjY4sy0MuRgKe6D1O0VqLWg3ha6LRZCDPjU=
      KAAMEBOTT_DB_PASS: AgBhgkMHB7YZx/9vuZaE4JrupUU/PQ/W3N2ennHiRxbeuQ08ho7mb3Ag1oFl5vWYM/DaD51TZSluMM9dBfg+WxMoRFjpwq9kCBxpsZCHRknNI4GY3j5QjYFoujcyvaOQUyDZH4Nmx8wViScd+DIfjX5Q+nk7b0DnJmevCRAqAD64uwEIbkbXlEXFhY+PKY0mFCwVKMiMSF2Xd8/ysCdokkpncgE24co4zK84/SPqTV1Lt/LVtOaRtxYlWZVNrsYU1pvZz4oYQDEoOKyZhIqboAHphbWGhXfZpgPkWq4kuTi82RHxhCrepkGU2Llr1v+jVFi9lvIaI4nsmMDia3AW0NOoDbkOJgSUFaNHgwnYP2zICEvnFTb11wJYiqm/060nItJU9OUAPrNsloIpXQGJY+/Bk8ZHHWUXIRzv6NcWiB3x+tVE6wAMuvR4yI++C+giLEL5NIydgnxbaDxCbMHHZXJJ3Jbod1+v2gF8n3dvdrqKi3SKoleLYN3VVQpWurGCTn8lVXSzTbISWBDy+kuKq3lRSBs2zyDHQtUjEucG+M1CCuiPXjlZJc3pPQZEcTeiPuVLgrzS9Gj6jj2Q327MHYwjX9aSpnD+u6XUbkyK6mdx2jlH8Ibv/jaZkFVpkKBN4BBb/rVjgdJkRpEGPVZGuapy1TDVEpuNrZhEqf2AvhUdv4eg71hjLzM24ZJ7CY0bdihqi5pVBS3K8YKE2sPIH0cpSUvk19o51MvkCBDaL/F0MBYRAcDrDEk+xjrcORqoq5/Oyoat2QTayPszbko=
      KAAMEBOTT_SLACK_SIGNING_SECRET: AgBcqYzDaNCNtoI83JiB77baRjbqdkXNn2DRLWtHFKYxH2KEzhwRBZf5gTrGJjyPgSwaEl6wcpIPNi0Uxg5sa6uH0EX8gm2W0ncuiXx5sSQm+v2SP4vOeihAsYpWXP6UC/y6eWooIssVa4d0IIhi8/37oq0jtNX+9f9V4XYhraPsoGuHEf9LN3GJOOQHFkXE6A57r6twe7/r21gkFl5HUMwzZt0JWnVuDm4p2rvoYeS/GVrvq5lSzEsyASPvxEDdMKTHXEECFAZOkeXDl4Sm8WkjgVlSXxLmvTNH51u10fsYmO48HV1XynYOHzjKl/mmGgjyRD2McsgdYK9MW8SutjafhRtejRnBk2RhuAh4XdQsnj1q1VlGUAXrhxwIYvck6b6b8WtOYZtWlWCou5izLfB7CrXkHl9ziTMK9DOWrBGNKPTip2q1NBf0K41zajAt7ZeWdYAVl9p1aAXhaqijevcsZ2ECi4bsNVhDapxebBayJqU0Dy1Zx6HAAT5QX0vJ/s7EQSXA5TW7qYVKoV1LYgO+FiCDOhi0mN3wP3/IS3L5+r4ynj3+xPfn1whw3EcU4IO432hUL/BBs5sklDwAkfsIvnijLfqEXmyp6oLLZhhbB0JXf9VbSbAFYyTON9d7eVIZ1b0vlLb8OPtLY5CJMwrVxq1FnHR9UxuOLRj52Q0I2PT7XnrQqnjoRnQ2d9EFMCgCnc3cZEuYM/+y9mFy3EHLuT+9JX5sxTAnvn99gU7hkA==
    ingress:
      enabled: true
      hosts:
        - kaamebott.vibioh.fr
