apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kaamebott
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.75"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kaamebott
    image:
      name: vibioh/kaamebott
      tag: "202108312101" # {"$imagepolicy": "default:flux-kaamebott-api:tag"}
    config:
      KAAMEBOTT_LOGGER_JSON: "true"
      KAAMEBOTT_DB_HOST: kaamebott-db
      KAAMEBOTT_DB_PORT: "80"
      KAAMEBOTT_DB_NAME: kaamebott
    secrets:
      KAAMEBOTT_DB_USER: AgAawfgv9QL+8y+4YGszWVklKgfxTvtHhnpL4Kcbat3QqUZqaLhaLexAZhiBLRpsLSbLPMrm6LvvKp8Vk5ZcOR338llY7rLogrOqipDJgh+G5G14VHfaXsTrapWDtG3q4CmDXkpdvokl+Blx7re9QdznuDLfX1ULjg/49rurFcR0RagSfQnAqnOK7VSFjRK2kffpCkrRtRRX8nBcncjoQK8sXZKPAD/hwmse6iRSi8NiLqaZ/2qM2RLdv08t6OfwZrOS7MeL2TlLZ8k/rPaAPS99JEb2py1j7fzawbKicO0hZJ8tnEZiTk8R81nmrhNxfNdjH0jv381wgcojo0VFVZ8nf6PTPFhW2Ue7DEwwNgoyJ6mTe9766C0KI67/QgCo1VrWFBqjxuoC0YSE/YMr69vqYIzfQd5rUdmrSjUMUCDdNkidrR/GOes77JKBQWtGm9+8dQlb9AJOUmQZnLx9fYmnXMSAGRjzI71lO8mrUBYWN/xyfQlYXW4uN5znlVOsiHFYfxITMTF7tJ+bBeuhOO+awJ6oeOrQXWd5IwpJZrKxtA4F889ZsFNr/EpycpZ3SuwUBaD/2rKAaL6X9CaeXdgxvoRq+UdOvwaA6BpL9oL46PhxjxMwxyS85hVmKVAeKreVKbCL1eu7aeBVGLCgVLMzVy4/iDgROSX6L/WoVixqPjY4sy0MuRgKe6D1O0VqLWg3ha6LRZCDPjU=
      KAAMEBOTT_DB_PASS: AgBhgkMHB7YZx/9vuZaE4JrupUU/PQ/W3N2ennHiRxbeuQ08ho7mb3Ag1oFl5vWYM/DaD51TZSluMM9dBfg+WxMoRFjpwq9kCBxpsZCHRknNI4GY3j5QjYFoujcyvaOQUyDZH4Nmx8wViScd+DIfjX5Q+nk7b0DnJmevCRAqAD64uwEIbkbXlEXFhY+PKY0mFCwVKMiMSF2Xd8/ysCdokkpncgE24co4zK84/SPqTV1Lt/LVtOaRtxYlWZVNrsYU1pvZz4oYQDEoOKyZhIqboAHphbWGhXfZpgPkWq4kuTi82RHxhCrepkGU2Llr1v+jVFi9lvIaI4nsmMDia3AW0NOoDbkOJgSUFaNHgwnYP2zICEvnFTb11wJYiqm/060nItJU9OUAPrNsloIpXQGJY+/Bk8ZHHWUXIRzv6NcWiB3x+tVE6wAMuvR4yI++C+giLEL5NIydgnxbaDxCbMHHZXJJ3Jbod1+v2gF8n3dvdrqKi3SKoleLYN3VVQpWurGCTn8lVXSzTbISWBDy+kuKq3lRSBs2zyDHQtUjEucG+M1CCuiPXjlZJc3pPQZEcTeiPuVLgrzS9Gj6jj2Q327MHYwjX9aSpnD+u6XUbkyK6mdx2jlH8Ibv/jaZkFVpkKBN4BBb/rVjgdJkRpEGPVZGuapy1TDVEpuNrZhEqf2AvhUdv4eg71hjLzM24ZJ7CY0bdihqi5pVBS3K8YKE2sPIH0cpSUvk19o51MvkCBDaL/F0MBYRAcDrDEk+xjrcORqoq5/Oyoat2QTayPszbko=
      KAAMEBOTT_SLACK_SIGNING_SECRET: AgBcqYzDaNCNtoI83JiB77baRjbqdkXNn2DRLWtHFKYxH2KEzhwRBZf5gTrGJjyPgSwaEl6wcpIPNi0Uxg5sa6uH0EX8gm2W0ncuiXx5sSQm+v2SP4vOeihAsYpWXP6UC/y6eWooIssVa4d0IIhi8/37oq0jtNX+9f9V4XYhraPsoGuHEf9LN3GJOOQHFkXE6A57r6twe7/r21gkFl5HUMwzZt0JWnVuDm4p2rvoYeS/GVrvq5lSzEsyASPvxEDdMKTHXEECFAZOkeXDl4Sm8WkjgVlSXxLmvTNH51u10fsYmO48HV1XynYOHzjKl/mmGgjyRD2McsgdYK9MW8SutjafhRtejRnBk2RhuAh4XdQsnj1q1VlGUAXrhxwIYvck6b6b8WtOYZtWlWCou5izLfB7CrXkHl9ziTMK9DOWrBGNKPTip2q1NBf0K41zajAt7ZeWdYAVl9p1aAXhaqijevcsZ2ECi4bsNVhDapxebBayJqU0Dy1Zx6HAAT5QX0vJ/s7EQSXA5TW7qYVKoV1LYgO+FiCDOhi0mN3wP3/IS3L5+r4ynj3+xPfn1whw3EcU4IO432hUL/BBs5sklDwAkfsIvnijLfqEXmyp6oLLZhhbB0JXf9VbSbAFYyTON9d7eVIZ1b0vlLb8OPtLY5CJMwrVxq1FnHR9UxuOLRj52Q0I2PT7XnrQqnjoRnQ2d9EFMCgCnc3cZEuYM/+y9mFy3EHLuT+9JX5sxTAnvn99gU7hkA==
    ingress:
      enabled: true
      hosts:
        - kaamebott.vibioh.fr
