apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kaamebott
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.84"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kaamebott
    image:
      name: vibioh/kaamebott
      tag: "202207160753" # {"$imagepolicy": "default:flux-kaamebott-api:tag"}
    config:
      KAAMEBOTT_DB_HOST: kaamebott-db
      KAAMEBOTT_DB_NAME: kaamebott
      KAAMEBOTT_DB_PORT: "80"
      KAAMEBOTT_DISCORD_APPLICATION_ID: "882376778943971349"
      KAAMEBOTT_DISCORD_PUBLIC_KEY: d3acdcf3d7dc08c1d32714b3a51b0db4e40041059e075b274d94326011c20a31
      KAAMEBOTT_LOGGER_JSON: "true"
      KAAMEBOTT_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: kaamebott
    secrets:
      KAAMEBOTT_DB_PASS: AgCDotuFEUK2KqB/aAe9/DtANgaMq9gg0W2evNozDiBu+ujGI2ILOHi7fJovQI7gHnKHJ42YPmuDnBIiZg/vEPFcFcbHywKPu0HsucgOIdDFfhnTt/tUJ+lNDnp88CmIS9aMnhcMlfsG3e8B236LZr29wSELyTtLQ0U6u41pbkXFYFSIhUpFBXmWbk7Z/FqHPk6ge4T3nXbbqBlSiS+bLh+eALyq6yVcIzg5y4+6vzJ86rDp8cxDk2+OGVtviGXZtJm4nAul3IG+4iEOlq8sakNv2pIONo5XMXysJaIo7lsnKZ+caqJd6MMsVb9nuF/uWt7+Kp+N+ws/f7V1Jec6xgEbqhuXGR96ceVMArESvHsaRywv5JIOVFFXG6AxxLMkzYlmd9sWkNTKQVUPsJZUZKvZvs68wQX68Edpe/U0Y3aiteigmXil3zpbK26EB3ZNOLYtnWD7/YYvV4R1dGs50wnrK5xutxKzuJMrBJ9EtYvqdVnkYM83nHCPw8/0jTXa+bawbJvfqDQonMeJF6ArqiFxleiyuDYXW3QVSlS+6/qWj1q46hrFKplhhAUddZEY59xfF61Om29rxCbbcBfZgzh076MoJew9Aa9XR0u7d1w2P3yrQm+3tlNp12yTY4WnhF0Tnpw5X7Fby+xwuQds2wCJGlL6S484H/ZOEU6lIFa/KEzy2bWJigB6jKlfaumnHezw6sE4pXioxyMogqZAQyZ/rtEvSQT7rkzY4Hwa9og5BVl5+JEKUuEeeS2nf9j58kCBBqQTsdypYAssMDg=
      KAAMEBOTT_DB_USER: AgBRGfJ9ggMQLRvUKVLpUavkzr0qj2KIG7mNCUUBX+9bcDh1ZxUxw1OjT7FW9m6wP0acI2nrPPbcWB4Xndoath/Ql3dwXEMftxEUeddjLQbO8elUg7ozUjBhoSVoiqjBZ5lfCVWdt56LeELnhKay6j+mbd/atSNteDFbhAcMMnQT6cuK6bgZLh1UHByEByTJwZO3qEpgznLNzth4KRy/LSAi1VSBXT7NVaF+VDyV/ysKEUYl+mYyYoDm09Uq7wJ3ojn5xRHA2InidcrcPufRGpbUF2ZJoCI/vEBcozuIDpCcQ1i4+fVDEXABX/mqDtAaGaEJIFvSPbMVjdMtTEvO36of88imKFgdQxVLY4EhJNP2nbmj66JAWLFybVOhs3yjyFCJJKxMQi07romju8K2x0Ce+qRZgllvg8YwFFBXXcfTV8VE6CQOhF+sQBwUO4O3hctl94LRsXYoMv9+upf/YtzB2A/h980uGHNZWgDAKM5fzWFhRgSV0vBOnBtIdVFw9tyvyzXXX8IACOdieJ9nv84kuoivEACqwSlFvPg7c+Th0pPTZzNY6WUFAwu1RaqPGixKX91RR2MF1Zf94KAY/9Xxzw7Vsf/z8mR7ejGH2zZf35Fe+3kxRygRuFj5SSMTAcBhHEnCxsIU2BwgfA1iQ+E3N53568K6Ejjd9LMehfkruZVX42aUrk8poFqpHiYoFM/sdR6OpadCUgs=
      KAAMEBOTT_DISCORD_CLIENT_ID: AgCbJHr6EDRlaOSv7eNlhlhuCy0MlhKdlGph10RQN4SVNswb/MK+bLuW5/m/5wsvMH7NuBd3dCmOLOPd8hbUBWh+41UcD9LTsRWSa1Y0la8MPhjwsh6u4hxISF9GgP3Az7EUv1MxlFNm1hTq8j8GAPA2jXrXH9y92V7uNQkZ+kLgUuexDgrAV5yZpBjg/K81b/ysSoBbfiWNf4rRzxG29jYb1nWxD/vgJ2GaJ3mSdhuOVjGk3iypi9Drf3YKV0dVTObvlwJAVPpIW7i2kKElhlpB3HM6Z0Eapa5yy7YcdKxw0q7JuSuOaB6Hh5xtIisk7s7b11W3a4Eor5TPI8QG6GOjsaHtHH5FIYnqHla8mo0DFFbO0vuQBY/06zLM/9wc78Rv26tXvIG02bjwF5xzCATH8FY8prfyP6ww0VeqaEe6wODcaB8ydKdNAOar18rWTsGtoVhy9pGdvClYCnaWny0PkoRCqEUUV4pcWvzwk1Zrtkqd0ZMNwNSJytyARCgImEkgeNw3ASTXkZF0FckNmP2NXsawz3Wkfsf/egTXmQv78cOYNOl1UlAuErhXD4gGGgUoyAUwBH7HtulIVcBL7SruNs/xP9f8CaToQ/potvQC1moX8BSLOa1WlcGEcN2bC5YImgqaSV8nUOLcjE6H4oiNUjY36GmB2YvV5bfSBePPLmXDc1Tuo5PTLwVdoz8CRxGZzrQGxUMLSjadEzWoRp47sn0=
      KAAMEBOTT_DISCORD_CLIENT_SECRET: AgC0myzfcEZ2IeXFhEOJl4k2mJ/iLdstrY34C04p5PQB9rQv/fPlQmHM6vJ7M6osEuTuI1PyLPlKudmV73WgDU8xNKHd5TWUiGh/mh0InagDVZrsbtuHhVlXY7kBB+xe/zbAVDiHUoMRkwExm0Fo2zzdkqt8l/xVakDivPy5ah77E3e7aCTsuLpS6Ghkm14sNa5CxfneyUlaqwfDXGghBD4YMF/EVmagejakm2KiUjiQWlFoLePWkZ2oSKmRamULNypz66dNH95CG8Btwbb3e3ddbu14yEKlvQcnI9aFG89Wo6Qcr1jhGv6shWlzJ/cvFnG8C4FQrLQhY68NFvt4w6oz0VfPJTrL+p73uLB7bQ3IIBZDl9M0vV1R25FoFnjrotqSQpW8PcvJB4j7g0hQAL9ygoCHPA2mM7zNgqkxWhL1qNFvsREAaapZU/dm2Mi0+g2x8GG8X6c7zYE27UUbXO/WznuYhzi/Y7e//1MBMH91EMXtS25bGF12yRU+MhADJgFNeYKCZur2NA8pebnw7fzgxRYDDeKquzAUbUfUDhxrX5liMbAvVLuD9Xtgl0M7yIlFgc2AKUyoTN+CZGNzoUykdw07X8HUy/zBKPv44gQvaIcN0GqBr/K+My82smeOHLxDk79Kv3mfMDPrMFF3vFg11EpJVum90SsbwDP88aOKM+fNUbuMIDw+QrkzBTizsJ4CxMF4PwyGZDPfYzn7Tmy2Y65IIyxsCodYMDom+MEpOw==
      KAAMEBOTT_SLACK_CLIENT_ID: AgAMdiqhOU+QTR/aW8QeUSIuvMqr+Tk/i9sPAq9u1BNM6JgIVwJ5/KqnrkyOQt5Rym8nL8+k2YdLgMY6Jz6a/4DfxVpFuhI6T+358Q/+Osoo+7OaOkf3xiAYfxRqJlX39WxATYrRyhYO0BmeZdMLZ1Oiak6mm3hi0MZPuHCorJAg2YY5OpOrjeA3zUHDgHTLBSCp4+a63ReYjqx5iR91PY9Msz6cn9SjeFNMfZtBs0T4p5BQtvNObn6tQx8q4ohiEz/eAKIZohfNjLVicFPshvWgtFFWwxT+hCpF7SfwTUZdOf/Q20nmUaOsOMj7sqFFmjygmpH8OneQ+s3qVWlPp/1nlIfuQ1NqpjE0E29KOoNeojjGTbJBcfDeJ8u8/65d0McKew1oYFejdqxby7wX1b0bMxzUYrZ9sulD6z6gdOYv51pyYjqa7vbfd0oTUzInp6hgeyFEynDP0hlm1NlNfv5Uj3TDEVQ/wdgKQiSAra/uGmOKXOqTmfKBwx7lbRfzqBLk4818208tfGXiHioXOtmr2UUu4dNO3FUiSNAY/1HdmWK1/sOzK+V/SDi8E4cRYXJ/cjFnx709TFwn039iRMRZjJeiKEodvlOUX4Pp8EdvM6itI/FNxUeloM4wvA91Z/2BdKmmnsQNXqcG0OhImvQ6WLPohDJVHbOq4f4ARypSzRwk3KzrQyWmP+/jTpSo9xvlvsurm58S4TR7yzgqnOpokwcFfbmomKR7epY=
      KAAMEBOTT_SLACK_CLIENT_SECRET: AgA/oA60iPZT8b+GepxbxjeLsnbsIib5E14nFEPJ7zqPfhvr7JC+uKljqImmmok4BrLLj9qtFcfCxVUc6Puo/fInKIFHqZwZiRApBoSVxjlk39ngESHzv/OKhX56UB0UlkEXh/OdkViBDfCllesN44DIFBETQ3NSt167CkMIz2waBq1woiN77FvDrWwIuNCUDpk0YY1WTKnFEz+DNsIz7CHHGeP7wwG5akIJgZh7crg73DfwY4P0+ojTf1t2fu1KiqlHSj0vAx9nj82Wy1NRkP+6xB/nMhGl6Z29Un/9YZ42Ct4175T68XQF1vhUdAZCCV/DdY1f63zOthm8USbbMFI4ZdPJcuoNwydxdtEnvKh5LCZzWYX70ond1FleWYujJ9xhzlQLb28zHT/cIW8WNOXywAxiP4agzwr5tKChO0hKLH2Q6qCHpy0feeFOkM0slb5hCaJaDCuAVICQ//CtPygkzARvTiorWuwKnelT0bj0vVXWHOk+rhtC9P6SaRUTsmjww/q0Y+1Ko3pLvxeneMT1+zz4F3Gib7e+IAYrxj1tMNi1tteK7pH5xRJncfhyUbdtBF4jJKJofIlcvYvO5mpfncsyIcwAMP9FXcat8OfAaSazzC3hNr1f4Q7nr+vVznDMgiuHzXG/wy3prXvZAfi6tmDV1moqLiReHT54Z/j/oE2zrNps2f2H4SFnbjXaKlACS6xMBjPVQSV+/yP8SsfC6YI41xRgQHiF1Om6r9x/lg==
      KAAMEBOTT_SLACK_SIGNING_SECRET: AgALTm+Mufjz0mJRucp8xnjbkaZqr9d+4W6etZCq1LzxnJp3lYc0WadM41lZT9q9wujpeJo1q8ak6qk235OM6r2VLlqdD39+VYPtFObkOTZF3EoOobLV6u5hxfcYyNHYlv16Z2sflS3nz9OzK2X0Rt5ogfAb96adLDTFB+OnG1OhnVnz29Xz+KLTr5QPXY0LlC5+Ds7SVBUcB3g/HOWn2/8dWLTm9s4AOsmTTJAs0y03R+j6J9Lpghoiuz7LZm3Mau3VnyIckHK8LBF3h3qw5V7rR3k4+syFZjOXwCRw3Jpqa/z5EIEDmzNkHfm1yPjDSmleE85WtfTxjdoP66qA10X1Kr3Nek8Jj8jM+gKYxFmpqsRAfdc3JFs8wX/le+A8lzanZD/OEc+cNt78HUjICgvcct7gZ6h+mMQ+dmoArIkdRlG7l+b42PmUNi3bRTwww9g7+zdIe299ykjx+333q3i7Duzarb1GbfZvcg87py6p6rl4T37vWKkP14H+WpxPWqhcL8QyPO7uzXhBN3MddgF+RJx0RccWesHPaYOdwLhkcQESHrGDb2ZKKRof7agSB548BHgSSBtgmoZwgwpWkCaoSSytPDbkoTMb92hsWCk6PTIJwIG5nYEQKHLOKHGLbX3p+ypaY1DK1KsUWO3ZCh70UzO4r4Xg5A5EBSInhiAdGLBOpIcbSljXjVfsNtpRt1LrT1dUaJDHMAFY5tAAW8G/p+TAxDW8zGXINAKP+5+SPA==
    ingress:
      enabled: true
      hosts:
        - kaamebott.vibioh.fr
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - kaamebott-db
              topologyKey: "kubernetes.io/hostname"
    pprof:
      enabled: true
