apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaamebott
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.3"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kaamebott
    image:
      name: vibioh/kaamebott
      tag: "202407021131" # {"$imagepolicy": "default:flux-kaamebott-api:tag"}
    labels:
      tags.datadoghq.com/env: "production"
      tags.datadoghq.com/service: "kaamebott"
      tags.datadoghq.com/version: "202407021131" # {"$imagepolicy": "default:flux-kaamebott-api:tag"}
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    config:
      KAAMEBOTT_DB_HOST: postgres
      KAAMEBOTT_DB_NAME: kaamebott
      KAAMEBOTT_DB_PORT: "5432"
      KAAMEBOTT_DISCORD_APPLICATION_ID: "882376778943971349"
      KAAMEBOTT_DISCORD_PUBLIC_KEY: d3acdcf3d7dc08c1d32714b3a51b0db4e40041059e075b274d94326011c20a31
      KAAMEBOTT_LOGGER_JSON: "true"
      KAAMEBOTT_PPROF_AGENT: http://datadog.observability:8126
      KAAMEBOTT_REDIS_ADDRESS: redis:6379
      KAAMEBOTT_REDIS_DATABASE: "4"
      KAAMEBOTT_TELEMETRY_URL: datadog.observability:4317
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/kaamebott
    secrets:
      KAAMEBOTT_DB_PASS: AgC2j7r1KfVZqU86G3I9H1jKg4iYVq10G29RYP7CEtkuFy17kfWSX9NMxhc3K6z6yWCx32AkInWdxEDM5NuGxC94ZC3Z+46ijJmjwefJQcvt9B/pJEziIyFK9o7IOkCJKq2CQotoWjdn0ORUmuRdIcfX77V/vRncdHDUEYrQjnaLw1l8xUaBqePdSp3BDgAJK7kBTN8L34tDf4SkvtM50WeDI+r7HY8+//As+byqWXMXd8n/BFPw89fKZ1JHCylSsyVm6SMWwgx5eU1wyrFYmrN/nLk1e/GCuUighrMiUcAFuxvnGPb8eA0Oy7LGHLUVvSkh0yFbEJpAFYEyOSYrZOtzjuviyRHdRc/wty3UwYecjprHMklTMs1f9VpC4A+2LOH0YRU9gup7Vg0Nvsdi5XxHJCDJpsL+J4/EMqbl2jKq2JYAw+c3o1nTIU2CPTbfHBymP+Pw8uIic6D8nq0cfjBwmp6rZFkjR897D1QK1kDoW5dqUpM0obS8l1IZTJ92GyZzKMs+rLWsNKBdmwD2C+1MRzBI2cfTYOxl8sl2heRsA6CB8htCwQZtUC4F5TQUmKW7ChJ0DbblpA3czIQjzrLsGYIemUO5/UrdRzULmHlwblswz3F1yFSTtuk4FmBWJ+R7zfjMOG7soc7HgrS9CUGBrB8Lh8F1C60YuodKSdd3RBWtqRbazfUzwD6900GAW3nK97lWNSsIpsztnN+OvYUIqTCWnQQ+BUJOVf6a4WLV/ig87UazCYTwWsSmfGnw1tR32zNkLkgwuZCdBcU=
      KAAMEBOTT_DB_USER: AgC6Gflz7qUtQIIbPyqxv2Tv/csJa9QAdXdz83PfXb8yDfneMl6M1rbio2zLbvy/PlSAEEh68lIMe672VX7w7JyFVUyr9Zu4bb0DabnNkMyP6oI5OGLsAkTjuwkZk2mFTORyLiFWDptsN7SARVGSqUwTEKCAZxKcPX3Zu9zMrEj9LXbcJZ2IXSac5XTZMsOAtDaUvaiUW5SvYm6bbk8TEa63mdiyEQd+et6VP4x+yI7G6zgo0PLJVWtDqMd45/GQFy6Q+bOryCvoHYSmzEoXydhRTmJ2+Gf3mDFUQ+9cZJaQVKhU9dWoTdwObdFCdhaCaSa1983+VIMjq9B1mxABDvzO3E48FUSt+umXlpeUYORFvuTGnwK7KMVHF0VI7WAOlqFxnn81WCiBFJMecd5LnUSKjlsVK0Dq0e/Sv0F5ifTW2GSNPS5LCUI3+ZvdyGjMZuNofNTSGDPWlmUilDP/PMj3QXAiYNFjX7ouU/l2fR6o2Toxr0+QPVRLXC/RBX68xBfpoG7xL5KyrCmNiBjItCawAKLSTStrRV4kGaCbRBXlicxRZHG5mR2xgtQBvUY8+Y503YytGGGNAd0R62jdH38TXcNv5VvkrK+8ZVTZ3/mQvCnbSu/hSdIJ2LZx3L4q/b53xgq59GYt16Yql5JHfpZC0b9zZ20F+C8W+jTRWs2sWqRLcfg9d2QVCDtJ4ZW/yRBlVy7cmtOyJto=
      KAAMEBOTT_DISCORD_CLIENT_ID: AgBPnjjD6pwkTLnQNU0AR0bXrC9Y7TvfWVbDOaeIxQcnWrKSeBKNQ3joky0PJALfGrmd8L35vQ+UGyAEGlI+xa9N/AIoCMi4oiGaUJ2y5xdtD/gGlYvHjyqqZYnnEt9aoc6Gg+k1mp1XbbwiX0mOqE54iTOS4O7zKG40HTvgV7RC9IFQFG2hhIzihVLK953UYiGcH/3FxwhijCkmc6vdLehY8ckkg+DGELp1TPommDSSSDRBFh+di8cQfG4FPwrB5kS34tUdf5cp6GOqfHthV/YDbrSuDbGLgwJKA4FieV8X5JFg9WwZ5aNZ/SUOHMTB7kK+6X6U1mZIZX3XsfNUA1lj8Kf1lLayu+ZTgU4HTT2Vq80SBCj3r31nJy2z6D+IP0KXU4mSvOzyYLl3AYn/hjFnt98Fn4XgCixangNtZUFS/TQm23CTUhyfljGqnDZcRBcjRvbnd/F9tjL7hxaH2Ct15GIQGC1jhZZ+Z3BEcliAENoEW7TGvVR0J0rqsKatYqKeE+xH3Skd0qCzMCTYbTCyApOioLweqTkH29Xm8VnXzPncy8piT36NKxsx9nF0fNNGGRpeL18k2Jwwj8GwH7F6cHLhpZpqHy3bKRtnnHpRTaUbrcSA9XuiVWDtMdsJWxhE0QwBs3Kr2/3oaRms14OO4dwGVxuHCvMGACdqZ4pjoNiT2DCSzI7o2LnwTSY6tV45RD6w/5rpXRKoRZl0/B8ups0=
      KAAMEBOTT_DISCORD_CLIENT_SECRET: AgCL/AhWS+DwXoVaNYdRp2syzkadWb/iMhHJ9r5xCwxdXqyBrMajwXM8Yoo355HnuqkNuyQwNnJ25IDFfclFX4tvUxoOlcfHCHEa5Buhq7nL8Ecbt0ZxlXXrOjLOvEysY3qH4lEpYKLPzrq8UMt++4GykSuap1OArI+KEm17uo9iS163B4HmJHu/Mtkdr3+DEpDVPCvpcMd4Qjzaw+r6+ufEZht/pcbmW6islU62bs61Rt43DLHZmvbgPVIdz4YFDv89IobB+ThHBWZsArqyKk/H5VnYNOU9WOI9F3DbeJ1YwcBLa1ssWJ/bXg4Kp1a0oKcuhCRWzKh6tZrtxQmwx/xUnsaAoPkL3b/ZvosM6yRfn8vD4hvTu/FMxFNl9sHPcnu4mRFCFdJnQWKhyrAQQAaHIg9XxVEjJLcFy4ozSLAfzLgATPAu/7AGikQUaGz1UXwSqXqov9hM/TxlhGFErmC89Jxzg4PQTi1YLAS/2AlGcs/Bmip7TBxYFkCZZd7BazVSxoncsaJ0SkGEmnJFM7/oGcrVZhxpy6O1KjIJZSqAZM46cXjcy1XRrfR93WCtH9NRc6gKaFhWXlLWCtuFOAkQzUWcVccqF8JbxLXQ0hgrwpQwsTJmwlLNqvuWnOHyLpGF2wyahzXHRZWxlSgf0lAxm5TLa6ByVYCxQToujlXUEJUAyriWE+BFQJvjUk56dR5tjhglf3e37d+IlFN+Q16K7hOCI87hi5dDinKdUsyY4Q==
      KAAMEBOTT_REDIS_PASSWORD: AgBnx7YCFLk+fBzO5i2ejCHBGrNP9wWXen2o9k4x4gsZz138wjWJff5jNHNlHtq6BiX42pkW0yLIsJjxV7fE5x1jzFbOC5s0Dx1dUd28eT/Bv6JjEtciYfiz2jjFq4qz4yNokw0SYNLa17y77/GCKl9n2nOIuqK9/+XazLYoBAuFFxkYXrZTUUQWcXfmKodONnRu5JLV8E8iqHC6Ur8sJ5M3h1Sr18/y40A0CNLRlscYp13HnxAEtC3znZRagZ6l09Al95BUNtMZ4LIaDBzi4YkcIHvpS7gPeae3EmJq4UtOLRPKJ+M+KM1DsZ+fu6QPAoQ0TJPhcj867RU6gC9xnO/V6rKCp4r8kAIep4gKEzhLj9tHAVhWqJeJePJK28tKAg4X0hRhNcqgrpTPj6RF5ARDpv4WPVh8bLcwMGq/eUIlKavpGXWCQXson11FWhqEoMM+48bR0fvhI5j1FUsPPSxG83hWTdrECfvoJpWxHaS6l+U1PvV+7tvlx37MWzzquMwJWlwkoK+6JHFT42/fb1ZSneZ1a93bsm6/a4yoUTEwdWbxj5Wb455idIFUWB0kOJtgZEJP78yEFTwvc7HMSsJscpVvEe9vGIMmvdsqKGykmhYxTisF+13hv9zd6MhNOei8UNRVo5foutewybH531/zLT7yNlK7O6oD08pzVqO6+CbT/3xZxBmtezVtH4kb09LbV6uCK8D7eubhSwXv3qUsUosNb4VtRIFTa+/7Ev9url/4YPZsNO99i1oPp61kuLneXZA5J1URxzurfkFqg38=
      KAAMEBOTT_SLACK_CLIENT_ID: AgCK6ic37qBvKpxrK16L8fdY+Jva04rgcZGPxEI8OiA1Jtm/JNPa11fdXEufvxkvxwO4A+YUFVzEpNsfYakCHR6T8gJRmzdz4HiflRMHbAZDqLdIKLjhWnyEtUX1Zq6hc16LlGdl6tJWKBwu6fZ+PAf+ANir+aRKpl4Uk7lGI8khHiSuUjSXhYvMwXuZKukREHLx0Ae/gCtvDjzofE9jWS8VL4O+F80GumYTcFPqgrvjICwklHhrGimTHCeHhzMOTF6DzSCT14RQhhwHpZmiQe7sL+uU8PkuvW1unYH1AVFAwW02e431Li7gfqs4hRUxhOwA5yQII78Tzvx2rNnrBbuP63LNoJUU9h5QB1B8O4AxXMzg7ru2+wWjKE5xP8Dy7WJ+mEFHhnS2RetJTrPrtvmU1G4Ps19otrGIS9K3NzhRofkkQxSE4OlCPRVgE5JhmOCxZ1effaW8+Cio1b1jWVQNZD7wjccooccX1hCLkYXUPPDaAQX8Zv4SCHHR8lG2Qi4Al/vqjhAdAk8JE3zi5OTYsMgd1KMs6D6p2V99yFmDgZshgZSu6bi6r3Xac2b/1aRopnh5wwPY36jmAIOQu/J/hEgqdDL3tekEbDEdDGrkjirEV+Ll+OjULoAk7uOzZSo74/eVyRdx3tB2t/lmxAGtJ7JvY9QdcxC5o9gEGxiQ8QfIm32oFm1bnsFdRxxZLpILG/eXmpZPqsPKVKhtDbFze+0tyZFeo6yVqng=
      KAAMEBOTT_SLACK_CLIENT_SECRET: AgB0JN7nu3ctuRr8fZR9cZ7pr4f/Ho9RXJZvObxlsAWGo/CZkw4CZlStzeJj+zhZLfrmlfJXa4WyLi1f4ohAj0I25183XY7iglJstSh+wgwi+Gt324YYVxEoveBC1/Hu2cC5TbNOuFMv/pqgI1jaSjQS7GOU6UbZuT2Jo5JRIonUfqk8w1zWuE+Slj3pXQh8OShQ3ue4Dey2Tg9HVwQy/KsksyAkwTBeBSX7+QOQNZh/8/SrZH9O/ErH/iUO/reP/wPFpBYdU99fS4/xgZm7cIK0zCtqeV40qQeMbpEy1mYaSw80bD2fsNN1hUuam9EJ4Uks9j/ji4ajiDyaGrEBHsZQVQLiXNVd+QcZ1JMZi5Tby6x9X8KKF1KofbOoHckwq3oVAEpb4PzzdkiOBOS8AYM5VXKTS1+sifbbE5TKwrgd9hkt0KZGRwOhllydgXK+afZyr6KXlvzdmuUOgzIB6VgEkSyuPv7KFTzheMEJUC6/GHsc0ltUZb//8b00plz6aYRFCcb8PAebSkjOsdpYPYc5J8styKhdZe85JJcmb3sIzKJJjQvNFYfsFE1x3qYJL9BEcUuADLKGfa7CSgrfgkJbMXbkmC9usCCGJxpr9xD5iFd5/4YSFylO1n7FvP2rGWE1q9EhyL8UqKb6hROFdWpSlycJ07Fu6XFUodiYpD+SigE5hhBg3+VChOomvB6JV/diZB2vnYmnZXPgbgu0wO6JmCeUtZ2GPyfqlyY/qUSwrg==
      KAAMEBOTT_SLACK_SIGNING_SECRET: AgAJd7lLP10aHQRJnhjoFWytjdO1Tt2DAzOrw7ayJK7DRyKRU+2+TGFTTNPSPSC2p54kU1DnBGiW+h6SYwSnNIU3tzfuWBBuwkIu1cdVycpn0Ezkszd0Z8us2sh+kav7LTbRarvc+9aCgblOjadyF06NBmadubdEveEFt266i9ShOiLxcKYnfco6RweOJDS2D0fl1SeytVe2ipFY1w9Byns46EjU+CWOZhPCC4VxcQJfQQC7eZs/8R1o9tvPVQR0Ah4BYrHbbMq2JUrgSLmRRx8PKRft0qzsh/Ca3dcQC+4Y9YXt1cXUnD92a8Tn30jU83hjM7Gkx/u14AMNe5wQvzb+8PSjfQF4q51pgqY5KHcHxqn6qbD7KpDI92Qt3ffjpDUuetokPxJFczCEAjhWGKOcurJac7NqJyf/zRCKrrEKksyeaebITYbiZ7hCHXFSfMhJ9DLxtx/cifipANOCeQWTz+tqGjn1P8ZzEAcHZzxbBRc9HjJN2eQI2ToMnlgtgeN2vobXcg/CHV5I+Q5N8AJc9rqGG3y+/f5EFiU+m/xxQ02sE9/gLH6RnvLk9Ea+Cj1BkQA7Ahq7leQ5GfSsrM7XAflKnJ49m9onHVV755+4aDeK4TpgDfxMp0kSV8afhxi6JQp7EJIOVz4DsHO9Gy2Z3/8z1irQ4GJe4iuPr5rGlG1swIEAEmoG8yxG4jVXfLH0VcPf93hOWAiswo49d6qc4auX/w7NBc4/zNwc1AufQg==
    initContainers:
      - name: discord
        image: vibioh/discord_configure
        imagePullPolicy: Always
        env:
          - name: DISCORD_APPLICATION_ID
            valueFrom:
              configMapKeyRef:
                name: kaamebott
                key: KAAMEBOTT_DISCORD_APPLICATION_ID
          - name: DISCORD_PUBLIC_KEY
            valueFrom:
              configMapKeyRef:
                name: kaamebott
                key: KAAMEBOTT_DISCORD_PUBLIC_KEY
          - name: DISCORD_LOGGER_JSON
            value: "true"
          - name: DISCORD_COMMANDS
            value: |
              {
                "kaamelott": {
                  "name": "kaamelott",
                  "description": "Une citation de la cour du roi Arthur",
                  "options": [
                    {
                      "name": "recherche",
                      "description": "Un mot clé pour affiner la recherche",
                      "type": 3,
                      "required": true
                    }
                  ]
                },
                "oss117": {
                  "name": "oss117",
                  "description": "Une citation des films OSS117",
                  "options": [
                    {
                      "name": "recherche",
                      "description": "Un mot clé pour affiner la recherche",
                      "type": 3,
                      "required": true
                    }
                  ]
                }
              }
          - name: DISCORD_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: kaamebott
                key: KAAMEBOTT_DISCORD_CLIENT_ID
          - name: DISCORD_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: kaamebott
                key: KAAMEBOTT_DISCORD_CLIENT_SECRET
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
