apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kaamebott
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.81"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kaamebott
    image:
      name: vibioh/kaamebott
      tag: "202204051620" # {"$imagepolicy": "default:flux-kaamebott-api:tag"}
    config:
      KAAMEBOTT_DB_HOST: kaamebott-db
      KAAMEBOTT_DB_NAME: kaamebott
      KAAMEBOTT_DB_PORT: "80"
      KAAMEBOTT_DISCORD_APPLICATION_ID: "882376778943971349"
      KAAMEBOTT_DISCORD_PUBLIC_KEY: d3acdcf3d7dc08c1d32714b3a51b0db4e40041059e075b274d94326011c20a31
      KAAMEBOTT_LOGGER_JSON: "true"
      KAAMEBOTT_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: kaamebott
    secrets:
      KAAMEBOTT_DB_PASS: AgBnndJjONXBrJF5VL7LNkUNYjhpFuFXR+S0Zi8XjIpkQA5byf7di/PbHlG+JMklG18TnmFz8lMzJs+Q+EU1heAjb2HQwDmkz2NFOjuNmey8FH+UcmkDGEmk7s87ZPCfP56/MG1lJQwJvONPqMSQlbZmMa9uYSpwnGFnd0EopGIyuaQUcAogtkLH0e0Xdcpcw/Ocy5LZc6swmjGfoL/fNDKecldaktykh0y8aGKuHBcreeN9W1gdXAr3CGW+2su1XrRwY1D511rDhmqAstoEvu0xffeagzRigiVSRTQ9hGSYzfiVNdk2y+CZ9jMmWd/uZ+aFT5yo/cz46B7yVODQh28kFEDUrNLgz46i6gpnaavLSReW0DNBUcdhKTcEriLwFVohCQmwFdgOz3bSRXUEcht9xXg85REwCvzJEW8Xcrv+Tt62EqM0jQM9ot6laA0lR6nx/pXPP0hwP8chjcd7QHx6c5+7MbwnMjyUJ0N+5JCtx470IGjP+t8OT3fAAOE7IHuhkA3ME0Uji6NBpHUywx3P9fEzWJOXY3IM+aN8X/iqRwYCgREvXTMn+Dyk1luaELr8iAJR9GFTYzDq4Bmx6qQFWYtXlrcMecwpt5WBQALRQfOp+0hy5LS16K+2eDkZhBq/A41N0Ap7E0nCW1phR8LC36HZsdNPQLxX4bKpL1InToGuQhUF66eiUchgk9waZvvxiotFWYU2TPXnSq6D10WNxuUyaIm1TturAkl59x4KAIODQLEYupzSL1ynZkeb/NBpq1i0MB1BTFQLCVQ=
      KAAMEBOTT_DB_USER: AgAdeY9MPuOdvBNdE9QJgyfl8QGMhHOP68O9JDRke5b446RgVCjbA1qpqbLu8yaWJHx+9lqIj9oR+AOZGkhENnaU39ZgRpjOd4SR5OgPgGviY8plT8oQsds2ykKdDdttzgwrnXYZuOcQdtEeJE9Lz8Q6QHQPtCC1BTbrMTYYe0xv7d2fCnn5pfD/cu4fkCdL2oZKg4HL59Na5OrL84K88j/vqEcOWLmtl+belaLxzRpUiZCDjrtHtvALGA7eElfnAkxnW/d2E0Uly50Wn7AYAHMdNlGLyvcn4uoYbM1a7Q5jqDWk3GX3bN7xppJOxcpB1lzmW7BodIcbUb5Q44DcgnOE/yxfHjGLNYrkVb2kk1TgPGMghH5rUJgZ4wcf3rijcV1CJ4QS4co2bUhlQfcaczG4/Txg7MAmQ1daFxnURoV6EMaRkPITU0HDZPeNCmRYcHglHxu2KBw1D8ioLgmheBnnyqcjHnHGrw4pFKALMcWHO8v8NbTE6A44aXyw7bZzeO0nTONSyhD0Yx2TsTVFukft1FrXcTVyDy5l/MS/ZBq0xDEl4s2JhDJzm/rLSVHBbGzfG/J0qXHmM7OZBr/6igz5trIncy1EqpYOImzL9BCYN+dKZ2hnk09ktijak4Ek7i82UTZ0V9w80I54UlBDeRZdkTVZQV28dp2CEhml2uPcVQ/0GkMK6KYUCM2+ljQbTwCIBQsELXG3yjw=
      KAAMEBOTT_DISCORD_CLIENT_ID: AgCvVC/BxVAxAeKvH5qhJAt9zh1yim82LpkXN1BOIzitqBvck5STbKRV0yMR2aGme0GLcyl5SEsu9yAuBnLZB6PDzJvhcKNJNbmhZfQTR/Es1YIkuQBKmcBWfRXRezvUvyBWw/z0oCjpwCTCHG6xszyJzyae75dBVZZsGZneTWlNtvArDEVdvMYEem++j8FfmiTWtEqmCkXY0dOGvX8z68x24pAjKU3jmuoKeVq6dbcCR4g2jo8gOR30L8XCrVBXGETuQl4EAZz908Q0841GspIcasQbp1f4qwksC9Fyq2sg+dW8bYjKOYd+w9IzrUK3DW0N4yhSjGRVEaRn0fcO8txH/NfvVmeWc9NWc+mSqSUYK+oSFGSknATJTotqOjPOCVqwrYdrIU4WGrUNK6MtUcO5b13GNluooVxoCI3B33X4I5MFQ+ASRFSQUrFMjQgmB6FBmImiaXAWSY8c1ypTt3tRCvSx53mPloE5wEIufcxEmOTEEIhuh7dll2txM1L2BkBs4qgUNvR8X4Qg7n47AahCeYpbEFb1crFsk+Eg2qtoKUt5XcE6ixpYNT0KwxdpmGDaBs8/NzbawEiYmh96ij7lLo2vJMhHIiJfP2GFPnPKY5Jtdnrrjqfkcaesh9P2mtOmoVgpVdEPBXbFZH6bdUghFQ9zv7wkFBXefQiB6KprVr8cMG/59PQIBuxvwN7BQYiA9U5K5P1SfiJde8zzk6yhbKw=
      KAAMEBOTT_DISCORD_CLIENT_SECRET: AgCxN8lEun4jiznswSUw4vnCW/u1lm7aDAAKpQF4nGPgpVCsr5iPTrecIIK2mhIkfX7M4OX32z8jZYaluIeruhar3OZVNL5Bd4Q8xv/wwNi/U1ebxHR+MZ8bRAPB9T/OSKPnDAdEnPMyyv3Jkv12h9VJFm6+bzZYdoT9HRClI54ebKsL/eqgBv9qz5MnbkJZLsjfOtkY15GjQN+NT/53aQVWwrL3aPZwwtDyqifWKvPPwbIjwFUt6A8BnepbSzt9Q1nQ3YN+yO3QOUWvtY4U0O4hmiKDIcrhsCuZ9IXu8+YcoPeDaE/BUFI+EHCt3J7KNYSnB5sw9chliYuJ7Rxoz+jmdybO8QCqHuNQtgw+ZgUbzbWpwnwQzCP5TSBciMt1wrF1qFa7w1pZ7MDk/4ChKBjj1csZ24PuStoiyk6WFdLbg9LMH1pU32+9SPhlOU+k0HRD3J+SaPe0xtdZ9LX9UIS7ASiJrHDY+mJHBocpts9ZHndepWJRQwHj80q7a7mPyStENa2tVkm5ZLnlYocKQNe48FEZk2RFLcMbY5eG/qPckKG9rNOPPoh3oK0QRLg0pIG1LplkiRJVp3TMaaTV3D2Ad23+fjusEi4plAHvXnamjPCV3mJlMT/AGR/3BuSNFsD0K48pLkndeZ6iwf4MCYsJ4hjeQvcbt56E3znbDyeqkdZkW6XR5LtHvaLAcgyEa/JioDLROjvY2NovvMPdf/E65J0ghS63bLfOt2p22LxWxw==
      KAAMEBOTT_SLACK_CLIENT_ID: AgAWXjHTtW3PvYUufooEVZN3Tz3e20QeVwPHD+Y1NjwZtOwvF9qKcrMth8ebdz/TVQ5/aXz7EPM8zp5HyOkJPR5XqiyQ37D4501nemXLd2MNnIUFZ4+zH4GGupwESRwxkoINiByBLVgCYW3dUexTXXhqkLOS3bGQ3hs0Xjndp++AXsmIjgI+ru2gt1NRqqZ1K2a1dY8TiPhrTPjovi/IiixQhW4ziR3rucjf3rGYRGCkJuEutF4m0gslaacSYA9+11mNiYHNR38WD0MPF5jjLa7Cqh3kiPWL8ddz0w89oadFs8+c2mtMlOl10QnPSDdal57GS8DBaLZflhOoueOj2n+XebAYj6ZTiwWFUxwneV0A9/jy6h1UU+50Uoo7ckI/WpQMEmw8GFt1q9pclCi06KjK8GkbwBjspXlhO1Ca73L7I9euQ/Jp4ZDX9NmfJiNttA7VYhB1dr9Pi0Rn457PxHT0WQVworJUuq0IjM1GbFitZ+HfZFgBCqTLnwqF/eCMPbh5B+tyZddyFeHOXr+cyv9BB3x5HMT+NkQof+FYrllScP3tSl4sTfWeER2oSBBL/zlCGH2ag3Miy/4uDIQ8ciMhCNmfNfGx/ocNqAXVCBILWFAngj5jPL+OwwaqkZP1kWfZsVeN8vrH2Rd3s8AOYWT2su9gfW+fnybEKRGQ4Huhz2eiUOg7xWAHmNMAGliv36QNyTyzUbV4guPiZeDfzjfsieFaJRD4j+8o348=
      KAAMEBOTT_SLACK_CLIENT_SECRET: AgAoKnMpdaBgFL4a9BWDwwu2lj2Fon+o5WOxu0M9POI8J84aPtE52rhXNjnqVdMkuuIk4EMakBrkI51xkOURgh7qgGf5da7aoFL6LfZcHdW07Tsvjv9h/FOAcGfO5pKWSvoKO3pe6FMfjqH1DJG37Nk62UH9HkhTnwN/1zJ2SXJDNimt7djMZdeRl/J7YCGzwgdOo13P5gxMxTndIbPaI/YOi1TJxfOva+OoBKxHO1wSCPgOsZYYsw7ikQNDGVJf50oUUx7dLI+6VTTcunABnvD2nu6pzlsBL0iCS3CVzpzS87T/wkcw617r3UsJ7qwEJ31ALS87J3vCSUzKZnCCo/dugLtbJftTVgCqbC8EjPujjvzsLwXtV2rJNdoZg9vSHjLZH2l+raqYSBnwVp/p687k6idNomUL9arb5QDoZ2dKviGyz3q0M66H/+yIbqtN1w4+byK3jvpz6iUKnP2og3tZyY/27/PEDeyKP8A1pN4Q1MtlsxUcFx0AUc6Phga8IRjMaUeQpuBeCTSkfCUqjcUkjIzhInGyL/Rph+3nm7GjRjI6FGPiRIHrd4XSjchazZ3Ocv5oTlqOtKn8ZbTmLWrt6tuGfNupYh7PLctvOVc5HXnJNl6NBX4kQzc5D4duboJpe3LCl6fJvC+uoGEWSbZVqOTHaznY1Wo4/WG11E3KxNPOMiDQhpQGFMMubyjS+P0K03B4Wszwp0kZqL5FrDOo2kR69AJxNoblnO0/e1AxRQ==
      KAAMEBOTT_SLACK_SIGNING_SECRET: AgCMZVo1M/jA+PAYWsHh4ZKUIn+G005MMHJHwF2+YGJsEpdi/DTRg7X1Ekcvkf3qT4hsI84JFKJMwmQO1ge7YvvjT+dYZ1D+9mkX3R/O+C5PhIXRKpg/hJWyLHo3hswgyrEoC2NchrzcrqO0aqEGUukt8VEvCpJ9ue/tQW3wxa1q2bZ/m4dgEUhmNEoE+SLINP7c39EVEJwdI8EcCRdDSUlZmz/BAVJtGpv7P6lJhMX8as0AMYmPenvI4T76Ib0JOV3qO3vddB2OutF9H88YPzgH/g7cbKuGDqu/toZ727180XrLICzfE09yWVI7fD+hFq1hNNFUNs3lk1pyDPQcBTXFhwx2u5vAm3jD/6R4RzTjxZx1eavwnzIrQez/b/esAq4YHMBdWRd/bLd2L14c46TdkKYoZPW3i/BCz2UvSChtqJwkbsa86sU8Wwf2eRl/3JIQjtGXm2wl1w/Btx2goMPQViBbirpuMpQ8Sa8oX4GkqnZGcTkPutQdjspRGOKFqSISecsLbAVUDaMvjnhSx4LLhL7gJp1ycB5EXezmvuQOLYhV8KIbUaM1p+vGCs8pc/KfFP6ZRukaxdKIc6Ylbb0IOGDzgyTjDXWHZrXKaLt6mtPSNoRWEbPjSb7yAVb/hIq4dX4dTj1VTh3sa+huMiPpzJ4Id1uqVs6PUmrmxG31hDQXWG7BX6bxMHH3nC2uLXN9irkHj/sLITpecM2Jzo1kdGLm217yUoZn1ogXbJA/bw==
    ingress:
      enabled: true
      hosts:
      - kaamebott.vibioh.fr
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - kaamebott-db
            topologyKey: "kubernetes.io/hostname"
    pprof:
      enabled: true
