---
apiVersion: batch/v1
kind: Job
metadata:
  name: kaamebott-discord
  namespace: default
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: latest
    k8s-cleaner: "true"

spec:
  backoffLimit: 3
  template:
    spec:
      automountServiceAccountToken: false

      imagePullSecrets:
        - name: dockerhub

      restartPolicy: OnFailure
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: discord

          image: vibioh/discord_configure
          imagePullPolicy: Always

          env:
            - name: DISCORD_APPLICATION_ID
              value: "882376778943971349"
            - name: DISCORD_COMMANDS
              value: |
                {
                  "kaamelott": {
                    "name": "kaamelott",
                    "description": "Une citation de la cour du roi Arthur",
                    "options": [
                      {
                        "name": "recherche",
                        "description": "Un mot clé pour affiner la recherche",
                        "type": 3,
                        "required": true
                      }
                    ]
                  },
                  "kaamelottgif": {
                    "name": "kaamelottgif",
                    "description": "Une vidéo de la cour du roi Arthur",
                    "options": [
                      {
                        "name": "recherche",
                        "description": "Un mot clé pour affiner la recherche",
                        "type": 3,
                        "required": true
                      }
                    ]
                  },
                  "oss117": {
                    "name": "oss117",
                    "description": "Une citation des films OSS117",
                    "options": [
                      {
                        "name": "recherche",
                        "description": "Un mot clé pour affiner la recherche",
                        "type": 3,
                        "required": true
                      }
                    ]
                  },
                  "office": {
                    "name": "office",
                    "description": "A citation from The Office",
                    "options": [
                      {
                        "name": "recherche",
                        "description": "A keyword to refine search",
                        "type": 3,
                        "required": true
                      }
                    ]
                  }
                }
            - name: DISCORD_LOGGER_JSON
              value: "true"
            - name: DISCORD_PUBLIC_KEY
              value: d3acdcf3d7dc08c1d32714b3a51b0db4e40041059e075b274d94326011c20a31
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: kaamebott
                  key: KAAMEBOTT_DISCORD_CLIENT_ID
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kaamebott
                  key: KAAMEBOTT_DISCORD_CLIENT_SECRET

          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
