apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kaamebott-discord
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: "0.0.8"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: kaamebott-discord
    image:
      name: vibioh/discord_configure
      tag: "latest"
    config:
      DISCORD_APPLICATION_ID: "882376778943971349"
      DISCORD_PUBLIC_KEY: d3acdcf3d7dc08c1d32714b3a51b0db4e40041059e075b274d94326011c20a31
      DISCORD_LOGGER_JSON: "true"
      DISCORD_COMMANDS: |
        {
          "kaamelott": {
            "name": "kaamelott",
            "description": "Une citation de la cour du roi Arthur",
            "options": [
              {
                "name": "recherche",
                "description": "Un mot clé pour affiner la recherche",
                "type": 3,
                "required": true
              }
            ]
          },
          "kaamelottgif": {
            "name": "kaamelottgif",
            "description": "Une vidéo de la cour du roi Arthur",
            "options": [
              {
                "name": "recherche",
                "description": "Un mot clé pour affiner la recherche",
                "type": 3,
                "required": true
              }
            ]
          },
          "oss117": {
            "name": "oss117",
            "description": "Une citation des films OSS117",
            "options": [
              {
                "name": "recherche",
                "description": "Un mot clé pour affiner la recherche",
                "type": 3,
                "required": true
              }
            ]
          },
          "office": {
            "name": "office",
            "description": "A citation from The Office",
            "options": [
              {
                "name": "recherche",
                "description": "A keyword to refine search",
                "type": 3,
                "required": true
              }
            ]
          },
          "citation": {
            "name": "citation",
            "description": "Une citation de film en français",
            "options": [
              {
                "name": "recherche",
                "description": "Un mot clé pour affiner la recherche",
                "type": 3,
                "required": true
              }
            ]
          }
        }
    secrets:
      DISCORD_CLIENT_ID: AgClRErFp8BdlbKiSm3KJH2cTSxlI9v3Sp02dzvCS5rndv3MxuwwSMgwHsdd08VqDNnjsmo/YB+I62PWUOEqOQ3IDbiim5FaTDFCJpOSC9PyVzu857wZyGXsfPJg+hqV2yWCnuhyCmn+mwylhadlhGlZ+nyFdgyATFGH+Ylnik4Y7Ox9FDVLlpeHBc36Cj8S0IvDZkPfHP5FOX/6TkN/tmJsOtI+sTTMufjMH86J2M83etJBAz6lQ7JQ/I5Bar+S5SwRbmu7Di6kLQyH5fcSol76uHCPbdSQxh6cPLZuCbMhsGeizSwzgXGW3nKMgyr+VO64lnsE7I4Mdy7kIbF1ZCib5JwwEcMJJKgJvbgLU6RsuCekvmREVYEqzGjbk99gniXFDQ8mOLnvuROxzaruTdz82Ji0fCpZ0rL/YI20DarZlHC79ekpAm0/6BqBuwWDAtc7IhXJiNkKPCLIVnvdVnGiapTrdvs3hYdSwOdvufUHzVv06KGqB36yN++Ol3BfyHzetCm6Dzc+dYVI6X9CGR2r4G35PVWS0z+16QIMdKNLiJML6KeVBgW9LjTr6mr66nLpsspGEKySPDV6XOD17kMqfVo8Mz9Y82EeMUoqRQ7iQ8zNt1zjSwkU9WEX4hRsPIm5arTaOhIKZfX4rKm93iuTHZaCj2cgZiFUrM/tI+Fr/gaoKcKtVignadPls8KrNI7uMvkq+ld0v2MQogQs91Y8+R0=
      DISCORD_CLIENT_SECRET: AgBYVF4iSe0eagdwEZpBUx/3UW3nLj6alt+4lqlfTvi41CPgyc8Rce9fLVUdrnQDbUSvlSF1idG8PVeuKKGahhhRFNY8e+vobTBIY4zjtfMDWREDeWl7uaFY2bpTVV3tusBa7quH8g4dem1s18Bo8t6G2F/WgGYcliyuxjBCWlYHok4sPJJzYTPGip5Czr62uI3mJUc65JTAajeGtMT1hMdHv2ShAnapnYrHymG6YmB2mm4oEYNFt1A6cxQOLJximPZoyme+ymwB47AbCCRtBRQ/Ay8SHkho4SJc9MRw3bqcodHkgVjsh7nEC0V32t588qCGJwfY0wIayUZl0FIU+2FcavIhkci1IzF2CiuxoyocZwb/F0Giwl3DEzupho5TB+MwkUjENdMCqYv5GCFYTpUt/kBdnaYEaOAZR6wmY9wWa75EzwAeb/BmrWtHVQN+1ilFb51gNUgwN0VleAuDUcB+sQyXxsQtI6KEgrlzeSloLulJ0wzsZcGBUioSzdhTRX1JW6weRBJ9W+JPrGA6zJFe6U28v2OSjdi5NjB3HbDMhtwC3MlUoNam+uAYtw3h0GK4n3oakoT/BiTL2OEUM37prQzL52uckINl7n4mLABn5t8BHCdB9Vs8d8wPxk0dWZK8hy84V09vpVUSJhx1Rq+yAIu3PjjAEAoJAU9YzgPuQWkmweSNxkSnpxzztw5Nx4UZRRg9X4M655h7NyqvKHhMuBGuYhoqA93g4CMprUPS+A==
